name: Build & deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal


  deploy:
  
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Pack Pebtos.GatewayApi.Core
      run: dotnet pack Pebtos.GatewayApi.Core --configuration Release
    - name: Push Pebtos.GatewayApi.Core
      run: dotnet nuget push Pebtos.GatewayApi.Core/**/Pebtos.GatewayApi.Core.*.nupkg
            --skip-duplicate
            --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
            --source https://api.nuget.org/v3/index.json
            --no-symbols true
    - name: Pack Pebtos.GatewayApi.Rest
      run: dotnet pack Pebtos.GatewayApi.Rest --configuration Release
    - name: Push Pebtos.GatewayApi.Rest
      run: dotnet nuget push Pebtos.GatewayApi.Rest/**/Pebtos.GatewayApi.Rest.*.nupkg
            --skip-duplicate
            --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
            --source https://api.nuget.org/v3/index.json
            --no-symbols true
    